### ISSUE TITLE
Error on new MonetarySummation

### ISSUE THREAD

**Issue by te-deum** [Pyrexx/zugferd-php#2]
Hello,

When I try o instanciate an MonetarySummation object, I have this error :
Catchable fatal error:  Argument 1 passed to Pyrexx\ZUGFeRD\Model\Trade\MonetarySummation::__construct() must be an instance of Pyrexx\ZUGFeRD\Model\Trade\float, integer given, called in .. on line 334 and defined in \httpdocs\librairies\vendor\pyrexx\zugferd-php\src\Pyrexx\ZUGFeRD\Model\Trade\MonetarySummation.php on line 92

I try to force float value with floatval without success.
When I want to instanciate a Pyrexx\ZUGFeRD\Model\Trade\float, I have an error.

It's probably because an old version of php run on my server (PHP 5.4.16 (FYI : I can't upgrade for now it's an intranet not accessible from outside))

**Comment by otzy** [comment]
php 5.4 does not support scalar types type hints. Therefore compiler thinks that it's a class Pyrexx\ZUGFeRD\Model\Trade\float although it's just native php type float.
Minimum php version for this package is 7.0, you can see this in composer.json

**Comment by te-deum** [comment]
Got it, thank you
