### ISSUE TITLE
Fatal Error when trying to build XML

### ISSUE THREAD

**Issue by te-deum** [Pyrexx/zugferd-php#3]
Hello,

I am trying to generate a zugferd XML but I get a fatal error :
`$builder = \Pyrexx\ZUGFeRD\Builder::create();`
`$xml = $builder->getXML($facturXML);`

Fatal error :
> <b>Fatal error</b>:  Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation &quot;@JMS\Serializer\Annotation\XmlRoot&quot; in class Pyrexx\ZUGFeRD\Model\Document does not exist, or could not be auto-loaded. in /home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
Stack trace:
#0 /home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(734): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 /home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser-&gt;Annotation()
#2 /home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser-&gt;Annotations()
#3 /home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annota in <b>/home/crm/public_html/_facturx/librairies/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php</b> on line <b>54</b><br />
> 

PHP v7.1.25
Composer packages :
> doctrine/annotations        v1.6.0 Docblock Annotations Parser
doctrine/instantiator       1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer              v1.0.1 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
dompdf/dompdf               v0.8.2 DOMPDF is a CSS 2.1 compliant HTML to PDF converter
jms/metadata                1.7.0  Class/method/property metadata management in PHP
jms/parser-lib              1.0.0  A library for easily creating recursive-descent parsers.
jms/serializer              1.13.0 Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
phenx/php-font-lib          0.5.1  A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib           v0.3.2 A library to read, parse and export to PDF SVG files.
phpcollection/phpcollection 0.5.0  General-Purpose Collection Library for PHP
phpoption/phpoption         1.5.0  Option Type for PHP
pyrexx/zugferd-php          v1.0.3 ..
sabberworm/php-css-parser   8.1.0  Parser for CSS Files written in PHP

>

**Comment by otzy** [comment]
doctrine annotation reader uses own autoloader. Try to call `\Pyrexx\ZUGFeRD\Helper\AnnotationRegistryHelper::registerAutoloadNamespace();` before calling Builder::create()

**Comment by te-deum** [comment]
You solve my problem !
Thank you :)
